name: Type Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript type check
        run: npm run ts-lint
      - name: Typecheck
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
